### PR TITLE
Move CS to Github Actions

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by simPod** [comment]
@mcg-web I've run this without https://github.com/overblog/dataloader-php/commit/8a78a51235d9b5902e44fd21b40439592d4ebb1f and expected some failure but the check gives no error. I don't use cs-fixer so maybe if you could confirm this works as expected?

**Comment by mcg-web** [comment]
Yes @simPod, this should failed since [header is required by config](https://github.com/overblog/dataloader-php/blob/master/.php_cs#L29).

**Comment by simPod** [comment]
@mcg-web travis does not fail as well. It fails locally. Not sure how that tool works TBH 🤷🏾

**Comment by mcg-web** [comment]
seem like I'm missing something, maybe the difference come from travis phpcs cache. Lets try with a next change, can you  [replace that](https://github.com/overblog/dataloader-php/blob/master/src/DataLoader.php#L41) by `private static $instances = array();` please?

**Comment by simPod** [comment]
now GA failed so I guess it's overall working and we can keep only the first commit?

**Comment by mcg-web** [comment]
yes we can keep only the first commit, can you rewrite the history please, so we can merge this?

**Comment by simPod** [comment]
sure done

**Review by mcg-web — APPROVED** [review]
Thank you!

**Pull request merged**
