### PR TITLE
Add PHP 8.4 and 8.3 to CI Configuration and Update GitHub Actions Versions

### PR DESCRIPTION
**Pull request by KentarouTakeda**
This pull request provides:

* **PHP 8.4 Compatibility:** Addressed breaking changes before official release.
  * [RFC: Deprecate Implicitly Nullable Types](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
    > Status: Implemented
    > Target Version: PHP 8.4
  * Added early support for PHP 8.4 alpha. [PHP 8.4.0alpha1 Release](https://github.com/php/php-src/releases/tag/php-8.4.0alpha1)
* **CI Update:** Included PHP 8.4 and 8.3.
* **GitHub Actions:** Updated to the latest versions.

### CODE REVIEW

**Comment by KentarouTakeda** [comment]
You can see the CI results for this pull request [here](https://github.com/KentarouTakeda/overblog-dataloader-php/actions/runs/9885679243).

**Comment by janlanger** [comment]
There is one implicit nullable missed in WebonyxGraphQLSyncPromiseAdapter::construct :)

**Comment by KentarouTakeda** [comment]
> There is one implicit nullable missed in WebonyxGraphQLSyncPromiseAdapter::construct :)

Thanks, fixed: c4619a3

**Comment by simPod** [comment]
cc @mcg-web

**Review by mcg-web — APPROVED** [review]

**Comment by mcg-web** [comment]
Thank you !

**Comment by jerowork** [comment]
@mcg-web would it be possible to create a new release including these PHP8.4 fixes? 🙏  Thanks!

**Comment by mcg-web** [comment]
Done in [v1.1.0](https://github.com/overblog/dataloader-php/releases/tag/v1.1.0) @jerowork .

**Comment by jerowork** [comment]
Thank you very much! 🎉

**Pull request merged**
